### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Link2Twenty** [construct-components/atmosphere#2]
EMALFORMED    Failed to read bower.json

**Comment by tracend** [comment]
Thanks for the interest @Link2Twenty 

This component is still under works but I'm open to hear what your use case is. 

Cheers

**Comment by Link2Twenty** [comment]
I just noticed it on customelements.io and was intrigued.

**Comment by tracend** [comment]
That's cool. 

[Construct.js](http://construct.tech) is moving towards an [all components](https://customelements.io/construct-components) structure, which is great but still heavily under construction. 

If you're interested, feel free to collab . 

Cheers
